import type { Metadata } from 'next'

import 'antd/dist/reset.css'
import 'styles/reset.css'
import { Providers } from './provider'

export const metadata: Metadata = {
    title: 'Home',
    description: 'Generated by create next app',
    keywords: 'This is Next JS!!!!',
}

export default function RootLayout({ children }: { children: JSX.Element }) {
    return (
        <html lang="ko">
            <body>
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}
